//
//  NewsFeedRouter.swift
//  VKSdkFeed
//
//  Created by Роман Важник on 27/01/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NewsFeedRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol NewsFeedDataPassing {
    var dataStore: NewsFeedDataStore? { get }
}

class NewsFeedRouter: NSObject, NewsFeedRoutingLogic, NewsFeedDataPassing {
    
    weak var viewController: NewsFeedViewController?
    var dataStore: NewsFeedDataStore?
}
