//
//  NewsFeedPresenter.swift
//  VKSdkFeed
//
//  Created by Роман Важник on 27/01/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsFeedPresentationLogic {
    func presentNews(response: NewsFeed.ShowNews.Response)
}

class NewsFeedPresenter: NewsFeedPresentationLogic {
    
    weak var viewController: NewsFeedDisplayLogic?
    
    func presentNews(response: NewsFeed.ShowNews.Response) {
        let cells = response.newsFeedResponse.response.items.map { (feedItem) in
            getNewsFeedViewModel(from: feedItem)
        }
        let newsFeedViewModel = NewsFeed.ShowNews.ViewModel(news: cells)
        viewController?.displayNews(viewModel: newsFeedViewModel)
    }
    
    private func getNewsFeedViewModel(from item: ItemsData) -> NewsFeed.ShowNews.ViewModel.Cell {
        let cell = NewsFeed.ShowNews.ViewModel.Cell(name: "",
                                                  date: "",
                                                  postText: item.text ?? "" ,
                                                  likesCount: String(item.likes?.count ?? 0),
                                                  commentsCount: String(item.comments?.count ?? 0),
                                                  repostCount: String(item.reposts?.count ?? 0),
                                                  viewsCount: String(item.views?.count ?? 0)
                                                  )
        return cell
    }
}
