//
//  NewsFeedInteractor.swift
//  VKSdkFeed
//
//  Created by Роман Важник on 27/01/2020.
//  Copyright (c) 2020 Роман Важник. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsFeedBusinessLogic {
    func getNews(request: NewsFeed.ShowNews.Request)
}

protocol NewsFeedDataStore {
}

class NewsFeedInteractor: NewsFeedBusinessLogic, NewsFeedDataStore {
    
    var presenter: NewsFeedPresentationLogic?
    var worker: NewsFeedWorker?
    
    func getNews(request: NewsFeed.ShowNews.Request) {
        worker = NewsFeedWorker()
        worker?.doSomeWork()
        let datafetcher = DataFetcher<NewsFeedResponse>()
        datafetcher.fetchData { [unowned self] (response) in
            guard let response = response else { return }
            self.presenter?.presentNews(response: NewsFeed.ShowNews.Response(newsFeedResponse: response))
        }
    }
}
